#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GuiTheme {
    pub surface: u32,
    pub page: u32,
    pub text: u32,
    pub muted: u32,
    pub border: u32,
    pub focused: u32,
    pub hover_surface: u32,
    pub action_background: u32,
    pub action_hover_background: u32,
    pub action_accent: u32,
    pub gutter_background: u32,
    pub gutter_foreground: u32,
    pub prefix_text: u32,
    pub quote_text: u32,
    pub quote_bar: u32,
    pub callout_background: u32,
    pub callout_border: u32,
    pub callout_icon_background: u32,
    pub checkbox_border: u32,
    pub checkbox_checked_background: u32,
    pub checkbox_checked_text: u32,
    pub code_background: u32,
    pub code_text: u32,
    pub code_toolbar_background: u32,
    pub code_toolbar_border: u32,
    pub code_toolbar_text: u32,
    pub code_toolbar_icon: u32,
    pub code_toolbar_hover: u32,
    pub table_header_background: u32,
    pub table_active_border: u32,
}

impl GuiTheme {
    pub const fn light() -> Self {
        Self {
            surface: 0xffffff,
            page: 0xffffff,
            text: 0x0f172a,
            muted: 0x64748b,
            border: 0xe2e8f0,
            focused: 0x0969da,
            hover_surface: 0xf8fafc,
            action_background: 0xdbeafe,
            action_hover_background: 0xe0ecff,
            action_accent: 0x2563eb,
            gutter_background: 0xf1f5f9,
            gutter_foreground: 0x64748b,
            prefix_text: 0x475569,
            quote_text: 0x475569,
            quote_bar: 0xcbd5e1,
            callout_background: 0xf7f6f4,
            callout_border: 0xf7f6f4,
            callout_icon_background: 0xffffff,
            checkbox_border: 0x94a3b8,
            checkbox_checked_background: 0x2563eb,
            checkbox_checked_text: 0xffffff,
            code_background: 0xf7f6f4,
            code_text: 0x334155,
            code_toolbar_background: 0xffffff,
            code_toolbar_border: 0xe8e5e1,
            code_toolbar_text: 0x6b625a,
            code_toolbar_icon: 0x6b7280,
            code_toolbar_hover: 0xf4f4f5,
            table_header_background: 0xf1f5f9,
            table_active_border: 0x60a5fa,
        }
    }
}
